resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astrofrog
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    envs:

    - linux: codestyle

    - windows: py36-test-cli
    - macos: py37-test-cli
    - linux: py38-test-cli
